site_name: Data Science Kitchen Cookbook
site_url: https://data-science-kitchen.github.io/cookbook

theme:
  name: material
  language: en
  palette:
    primary: teal
    scheme: slate
  features:
    - navigation.expand
    - navigation.top

nav:
  - Home: 'index.md'
  - Team: 'team.md'
  - 'Getting Started':
    - 'Code of Conduct': 'code_of_conduct.md'
  - 'Kitchen Talks': 'kitchen_talks.md'
  - 'Kitchen Lab': 'kitchen_lab.md'

extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject
  social:
    - icon: fontawesome/brands/discord
      link: https://
    - icon: fontawesome/brands/github
      link: https://github.com/data-science-kitchen
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/data-science-kitchen

copyright: Copyright &copy; 2024 Data Science Kitchen

